// <auto-generated />
namespace ErasmusSDS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gramos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gramos));
        
        string IMigrationMetadata.Id
        {
            get { return "202311112314220_Gramos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
